#!/usr/bin/env bash
set -euo pipefail

# Non-GPU preflight checks
# Generated by utils/generate_experiment_commands.py
# Review before running. This file may start GPU workloads.

mkdir -p reports/experiments
mkdir -p reports/experiments/selections
python utils/inspect_dataset.py --json-out reports/experiments/inspect_latest.json
python src/method_runners/run_3dgs_scene.py --help
python src/method_runners/run_mip_splatting_scene.py --help
python src/method_runners/run_2dgs_scene.py --help
python eval/evaluate_public.py --help
