#!/usr/bin/env bash
set -euo pipefail

# Optional SAM mask generation for mask-weighted experiments
# Generated by utils/generate_experiment_commands.py
# Review before running. This file may start GPU workloads.

python utils/generate_sam3_masks.py --split-root data/round1/phase1/public_set --output-dir masks
python utils/generate_sam3_masks.py --split-root data/round1/phase1/private_set1 --output-dir masks
