#!/usr/bin/env bash
set -euo pipefail

# One-scene smoke render checks; not a benchmark
# Generated by utils/generate_experiment_commands.py
# Review before running. This file may start GPU workloads.

# Smoke test only: one public scene (HCM0181). Do not use this for method ranking.
# run: 3dgs_f2_10k (3dgs)
python src/method_runners/run_3dgs_scene.py --scene-dir data/round1/phase1/public_set/HCM0181 --output-dir outputs/smoke/3dgs_f2_10k --factor 2 --steps 10000 --lambda-l1 0.8 --lambda-ssim 0.2 --lambda-lpips 0.0 --seed 42 --overwrite

# run: 3dgs_f2_30k (3dgs)
python src/method_runners/run_3dgs_scene.py --scene-dir data/round1/phase1/public_set/HCM0181 --output-dir outputs/smoke/3dgs_f2_30k --factor 2 --steps 30000 --lambda-l1 0.8 --lambda-ssim 0.2 --lambda-lpips 0.0 --seed 42 --overwrite

# run: mip_r2_k01_30k (mip)
python src/method_runners/run_mip_splatting_scene.py --scene-dir data/round1/phase1/public_set/HCM0181 --output-dir outputs/smoke/mip_r2_k01_30k --model-root checkpoints/experiments/smoke/mip_r2_k01_30k --workspace-dir workspace/experiments/mip_splatting/smoke/mip_r2_k01_30k --iterations 30000 --train-resolution 2 --kernel-size 0.1 --lambda-l1 0.8 --lambda-ssim 0.2 --lambda-lpips 0.0 --overwrite

# run: mip_r4_k01_30k (mip)
python src/method_runners/run_mip_splatting_scene.py --scene-dir data/round1/phase1/public_set/HCM0181 --output-dir outputs/smoke/mip_r4_k01_30k --model-root checkpoints/experiments/smoke/mip_r4_k01_30k --workspace-dir workspace/experiments/mip_splatting/smoke/mip_r4_k01_30k --iterations 30000 --train-resolution 4 --kernel-size 0.1 --lambda-l1 0.8 --lambda-ssim 0.2 --lambda-lpips 0.0 --overwrite

# run: 2dgs_default_30k (2dgs)
python src/method_runners/run_2dgs_scene.py --scene-dir data/round1/phase1/public_set/HCM0181 --output-dir outputs/smoke/2dgs_default_30k --model-root checkpoints/experiments/smoke/2dgs_default_30k --iterations 30000 --resolution -1 --lambda-dssim 0.2 --lambda-dist 0.0 --lambda-normal 0.05 --overwrite

# run: 2dgs_normal001_dist10_30k (2dgs)
python src/method_runners/run_2dgs_scene.py --scene-dir data/round1/phase1/public_set/HCM0181 --output-dir outputs/smoke/2dgs_normal001_dist10_30k --model-root checkpoints/experiments/smoke/2dgs_normal001_dist10_30k --iterations 30000 --resolution -1 --lambda-dssim 0.2 --lambda-dist 10.0 --lambda-normal 0.01 --overwrite
