#!/usr/bin/env bash
set -euo pipefail

# Render private set with exactly one selected run
# Generated by utils/generate_experiment_commands.py
# Review before running. This file may start GPU workloads.

# selected private run: 2dgs_default_30k (2dgs)
# Private renders stay under outputs/private/2dgs_default_30k; zip is created under submissions only after folder verification passes.
mkdir -p outputs/private/2dgs_default_30k
python src/method_runners/run_2dgs_scene.py --scene-dir data/round1/phase1/private_set1/HCM0249 --output-dir outputs/private/2dgs_default_30k --model-root checkpoints/experiments/private/2dgs_default_30k --iterations 30000 --resolution -1 --lambda-dssim 0.2 --lambda-dist 0.0 --lambda-normal 0.05 --overwrite
python src/method_runners/run_2dgs_scene.py --scene-dir data/round1/phase1/private_set1/HCM0254 --output-dir outputs/private/2dgs_default_30k --model-root checkpoints/experiments/private/2dgs_default_30k --iterations 30000 --resolution -1 --lambda-dssim 0.2 --lambda-dist 0.0 --lambda-normal 0.05 --overwrite
python src/method_runners/run_2dgs_scene.py --scene-dir data/round1/phase1/private_set1/HCM0276 --output-dir outputs/private/2dgs_default_30k --model-root checkpoints/experiments/private/2dgs_default_30k --iterations 30000 --resolution -1 --lambda-dssim 0.2 --lambda-dist 0.0 --lambda-normal 0.05 --overwrite
python src/method_runners/run_2dgs_scene.py --scene-dir data/round1/phase1/private_set1/HCM1439 --output-dir outputs/private/2dgs_default_30k --model-root checkpoints/experiments/private/2dgs_default_30k --iterations 30000 --resolution -1 --lambda-dssim 0.2 --lambda-dist 0.0 --lambda-normal 0.05 --overwrite
python src/method_runners/run_2dgs_scene.py --scene-dir data/round1/phase1/private_set1/HNI0131 --output-dir outputs/private/2dgs_default_30k --model-root checkpoints/experiments/private/2dgs_default_30k --iterations 30000 --resolution -1 --lambda-dssim 0.2 --lambda-dist 0.0 --lambda-normal 0.05 --overwrite
python src/method_runners/run_2dgs_scene.py --scene-dir data/round1/phase1/private_set1/HNI0265 --output-dir outputs/private/2dgs_default_30k --model-root checkpoints/experiments/private/2dgs_default_30k --iterations 30000 --resolution -1 --lambda-dssim 0.2 --lambda-dist 0.0 --lambda-normal 0.05 --overwrite
python src/method_runners/run_2dgs_scene.py --scene-dir data/round1/phase1/private_set1/HNI0366 --output-dir outputs/private/2dgs_default_30k --model-root checkpoints/experiments/private/2dgs_default_30k --iterations 30000 --resolution -1 --lambda-dssim 0.2 --lambda-dist 0.0 --lambda-normal 0.05 --overwrite
python src/method_runners/run_2dgs_scene.py --scene-dir data/round1/phase1/private_set1/HNI0437 --output-dir outputs/private/2dgs_default_30k --model-root checkpoints/experiments/private/2dgs_default_30k --iterations 30000 --resolution -1 --lambda-dssim 0.2 --lambda-dist 0.0 --lambda-normal 0.05 --overwrite

python verify/verify_submission.py --split-root data/round1/phase1/private_set1 --submission-dir outputs/private/2dgs_default_30k
python utils/make_submission_zip.py --submission-dir outputs/private/2dgs_default_30k --zip submissions/submission_2dgs_default_30k.zip --overwrite
python verify/verify_zip.py --split-root data/round1/phase1/private_set1 --zip submissions/submission_2dgs_default_30k.zip
